### ISSUE TITLE
Experimenting Outside of Upstream Repo

### ISSUE THREAD

**Issue by tajmone** [tajmone/purebasic#1]
@kenmo-pb, I've sent you an invitation to join my fork as a Collaborator, so that we may work together on changes requiring multiple commits and discussions, without burdening the upstream repo. When our work is done we can simply create a PR upstream.

This way, we are free to use all the Dashboard tools, create Projects and milestones according to needs, without having to worry about cluttering the main repository.

By becoming a collaborator you have full access to my branches, so we can work without complications. All you have to do is add to your fork a new _remote_ (call it `tajmone` for simplicity) pointing to this repository:

    https://github.com/tajmone/purebasic

Then you can pull and push to this fork by setting the `tajmone` target. Since all three repositories (the upstream, mine and yours) are connected, integrating changes in all directions is really simple.

But the main idea is to be able to plan, develop and test our own ideas using all the tools offered by GitHub — something that would be out of place in the mainstream repository, which hosts the public code and is focused on its maintenance rather than experimentation.

**Comment by tajmone** [comment]
@kenmo-pb, did you receive the invitation link?

**Comment by kenmo-pb** [comment]
OK I did receive an invite email. Did you cancel the invite, or does it time out? Because the "View Invitation" link in the email 404's and I don't see any way to view the invite in the GitHub desktop browser interface..?

**Comment by tajmone** [comment]
> Did you cancel the invite, or does it time out?

No, I just checked and it's still open.

>  the "View Invitation" link in the email 404's and I don't see any way to view the invite in the GitHub desktop browser interface..?

You'll need to open the link with a browser which has already logged into GitHub, for it's a user-specific generated page. This is the link, again:

https://github.com/tajmone/purebasic/invitations

As you can see, is a general invitations page within the repo; what you'll see depends on who you are (in terms of being logged into GitHub).

Eventually the invitation will probably time out, but now is active. I don't know why I experience always problems with invitations. I too can't find them in my account page.
