### ISSUE TITLE
Collaborators Team

### ISSUE THREAD

**Issue by tajmone** [tajmone/purebasic#3]
This is the list of Collaborators on this fork of the [fantaisie-software/purebasic] repository:

|    GitHub   |  PB Forum  |   name   |    OSs    |
|-------------|------------|----------|-----------|
| @deseven    |            |          | Mac       |
| @idle-PB    | [Idle]     | Andrew   |           |
| @kenmo-pb   |            |          | Win / Mac |
| @SicroAtGit |            |          |           |
| @tajmone    | [Tristano] | Tristano | Win       |

The whole idea is that to enable a team of Collaborators with full access rights to work on development and experimental features for the PureBasic IDE without cluttering the upstream project with tons of commits and discussions, and then just make a PR once a new feature is polished and ready.

## Ownership Rules

I've also created some branch ownership rules, so that each Collaborator can control branches that are named according to certain patterns mirroring his/her user name, so that other collaborators would need his/her approval to merge commits in their branches or do other Git related operations.

I've opted to use patterns matching a brief version of the user name, so that each branch that is named with that pattern is automatically assigned to its owner:

|     user    | branch naming |       base branch       |
|-------------|---------------|-------------------------|
| @deseven    | `deseven*`    | [`deseven`][deseven-br] |
| @kenmo-pb   | `kenmo*`      | [`kenmo`][kenmo-br]     |
| @SicroAtGit | `sicro*`      | [`sicro`][sicro-br]     |
| @tajmone    | `tajmone*`    | [`tajmone`][tajmone-br] |

Note that code ownership is achieved via the file `.github/COEOWNERS` which I've added to each branch, and which is not present in the upstream repository. For this to work, I had to create some base branches for each pattern (i.e. `sicro`, `tajmone`, etc.). I couldn't find any other way to achieve this with the free GitHub account and without using real GitHub Teams.

So just remember to always fork off from your owned base branch in order to preserve ownership rules, and don't delete the base branch or you'll loose the `COEOWNERS` file. Also remember that we should exclude the `COEOWNERS` files when we create PRs upstream.

[fantaisie-software/purebasic]: https://github.com/fantaisie-software/purebasic

[deseven-br]: https://github.com/deseven/purebasic/tree/deseven
[kenmo-br]: https://github.com/tajmone/purebasic/tree/kenmo
[sicro-br]: https://github.com/tajmone/purebasic/tree/sicro
[tajmone-br]: https://github.com/tajmone/purebasic/tree/tajmone

[Idle]: https://www.purebasic.fr/english/memberlist.php?mode=viewprofile&u=3792 "View Idle's profile on the PureBasic Forums"
[Tristano]: https://www.purebasic.fr/english/memberlist.php?mode=viewprofile&u=15012 "View Tristano's profile on the PureBasic Forum"

**Comment by tajmone** [comment]
I would like to add next to each GitHub user account also the corresponding PureBasic Forum account, so that we can all easily find each other on the PB Forum too, and maybe even the real name, just to make the whole thing less anonymous.

But of course, I'd need permission from each one of you before doing so, for both the PB User ID and the real name. So right now I've only added my own PB ID and name, but I'll update the Issue entry if you confirm that you'd like to see your PB Forum ID and links too, and real name (if you desire so).

**Comment by idle-PB** [comment]
I've got no problems with that Idle - Andrew

**Comment by tajmone** [comment]
I'm terminating these collaborative branches because the Code Owners feature is no longer available on Free GitHub accounts, so chances are that it won't be possible to further edit those rules in the future. Also, since their creation no one used them, so it makes sense to slim down the repository settings and branches to reduce clutter.

In case we'll ever need to work on some collaborative coding outside the upstream repo, we'll come up with a solution.
